Fixed a ton of screwups, and tested the code in the raspberry pi

diff --git a/bin/bootup b/bin/bootup
--- a/bin/bootup
+++ b/bin/bootup
@@ -1,83 +1,119 @@
 #! /bin/sh
+### BEGIN INIT INFO
+# Provides:          doorcontrol
+# Required-Start:    $all
+# Required-Stop:
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: doorcontrol daemon, providing control to the lab door
+# Description:       doorcontrol controls the lab door, giving access when an
+#                    an authorized DNI is introduced in the reader
+### END INIT INFO
 # Copyright (c) 2013 Alberto Mardomingo
 # All rights reserved.
 #
 # Author: Alberto Mardomingo, 2013
 #
-# /etc/init.d/doorcontrol
+# /etc/init.d/puerta
 #   and its symbolic link
-# /usr/sbin/doorcontrol
+# /usr/sbin/puerta
 #
-### BEGIN INIT INFO
-# Provides:          doorcontrol
-# Required-Start:    $network
-# Required-Stop:
-# Default-Start:     3 5
-# Default-Stop:      0 1 2 6
-# Short-Description: doorcontrol daemon, providing control to the lab door
-# Description:       doorocontrol controls the lab door, giving access when an
-#                    an authorized DNI is introduced in the reader
-### END INIT INFO
-# Some things that run always
-touch /var/lock/doorcontrol
+# Do NOT "set -e"
+#
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="doorcontrol daemon, providing control to the lab door"
+NAME=doorcontrol
+DAEMON=/opt/doorcontrol/bin/$NAME
+DAEMON_ARGS="--options args"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
 
-DOOR_BIN=/opt/doorcontrol/bin/main_door
-test -x $DOOR_BIN || { echo "$DOOR_BIN not installed";
-        if [ "$1" = "stop" ]; then exit 0;
-        else exit 5; fi; }
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-# Check for existence of needed config file and read it
-DOOR_CONFIG=/opt/doorcontrol/doorcontrol/conf.yml
-test -r $DOOR_CONFIG || { echo "$DOOR_CONFIG not existing";
-        if [ "$1" = "stop" ]; then exit 0;
-        else exit 6; fi; }
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-# Load the rc.status script for this service.
-. /etc/rc.status
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
 
-# Reset status of this service
-rc_reset
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
 
-# Carry out specific functions when asked to by the system
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON \
+		|| return 2
+	#nohup  $DAEMON >/dev/null 2>&1 &
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5/9 --pidfile $PIDFILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	#start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
+}
+
 case "$1" in
   start)
-    echo -n "Starting puerta... "
-    #/root/puerta/startup.sh
-    starproc $PUERTA_BIN
-    rc_status -v 
-    echo "done!"
-    ;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
   stop)
-    echo -n "Stopping puerta... "
-    #killall screen
-    #killall main.py
-    killproc -TERM $PUERTA_BIN
-    rc_status -v
-    echo "done!"
-    ;;
-    status)
-        echo -n "Checking for service bar "
-        ## Check status with checkproc(8), if process is running
-        ## checkproc will return with exit status 0.
-
-        # Return value is slightly different for the status command:
-        # 0 - service up and running
-        # 1 - service dead, but /var/run/  pid  file exists
-        # 2 - service dead, but /var/lock/ lock file exists
-        # 3 - service not running (unused)
-        # 4 - service status unknown :-(
-        # 5--199 reserved (5--99 LSB, 100--149 distro, 150--199 appl.)
-
-        # NOTE: checkproc returns LSB compliant status values.
-        checkproc $PUERTA_BIN
-        # NOTE: rc_status knows that we called this init script with
-        # "status" option and adapts its messages accordingly.
-        rc_status -v
-        ;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  status)
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	#esac
+	;;
   *)
-    echo "Usage: /etc/init.d/puerta {start|stop|status}"
-    exit 1
-    ;;
+	#echo "Usage: $SCRIPTNAME {start|stop|status}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status}" >&2
+	exit 3
+	;;
 esac
 
-rc_exit
+:
